#!/usr/bin/env bash
set -ex

# set env vars when running explicit multiprocessing:
if [[ "$@" =~ "--use_process_pool=1" || "$@" =~ "--use_process_pool=True" || "$@" =~ "--use_process_pool=true" ]]; then
echo Setting env vars for Python-coordinated multiprocessing
export RUST_BACKTRACE=full
export POLARS_MAX_THREADS=1
export TOKIO_WORKER_THREADS=1
export OPENBLAS_NUM_THREADS=1
export RAYON_NUM_THREADS=1
export OMP_NUM_THREADS=1
export OMP_THREAD_LIMIT=1
export MKL_NUM_THREADS=1
export NUMEXPR_NUM_THREADS=1
export VECLIB_MAXIMUM_THREADS=1
export MALLOC_CONF=background_thread:false
fi


# Use the following to always install the latest version of a package from source:
# --------------------------------------------------------------------------------
if [[ "$@" =~ "--update_packages_from_source=1" ]]; then
echo "Updating package(s) from source"
# update pip to ensure we can install a package from pyproject.toml 
export PIP_ROOT_USER_ACTION=ignore
python -m pip install -U pip -q

export package=dynamic_routing_analysis    

git clone https://github.com/AllenInstitute/$package
cd $package
pip install -e . -q  --no-cache-dir
# display commit hash
commit_hash=$(git rev-parse HEAD)
echo Installed $package: $commit_hash
cd ..
python -m pip install lazynwb -U -q
python -m pip show lazynwb
fi


# --------------------------------------------------------------------------------
# This is the master script for the capsule. When you click "Reproducible Run", the code in this file will execute.
python -u run_capsule.py "$@"
